---
platform: linux

image_resource:
  type: registry-image
  source: {repository: hashicorp/terraform}
  
inputs:
  - name: working-dir
  - name: concourse

outputs:
  - name: working-dir
  
run:
  path: /bin/sh
  args:
    - -c
    - |
      cd working-dir
      if [[ ! -f ../concourse/terraform/$S3_BACKEND_TF ]]; then
        echo "INFO - No pre-existing S3 backend configuration. Opting to migrate local state backend to new S3 backend."
        cp ./s3_backend_tfconfig ./terraform_backend.tf
        terraform init -migrate-state -force-copy
      else
        echo "INFO - Pre-existing S3 backend found. No requirement to migrate state."
      fi
      
