---
platform: linux

image_resource:
  type: registry-image
  source: {repository: hashicorp/terraform}
  
inputs:
  - name: working-dir
  
outputs:
  - name: working-dir

run:
  path: /bin/sh
  args:
    - -c
    - |
      cd working-dir
      terraform plan -destroy -out=tf_destroy.plan
