---
platform: linux

image_resource:
  type: registry-image
  source: {repository: hashicorp/terraform}
  
inputs:
  - name: working-dir
  
run:
  path: /bin/sh
  args:
    - -c
    - |
      cd working-dir
      terraform validate
